### ISSUE TITLE
Service down ?

### ISSUE THREAD

**Issue by kucukkanat** [ivanseidel/Is-Now-Illegal#10]
The service is down. The webpage is on but gifs are not working

![image](https://cloud.githubusercontent.com/assets/914316/22592354/b7690dd6-ea19-11e6-87e7-883737ec7dbf.png)

**Comment by kucukkanat** [comment]
Oh it turns out that you have reached your quota : 

```xml
<Error>
    <Code>InsufficientQuota</Code>
    <Message>
        The App Engine application does not have enough quota.
    </Message>
    <Details>
        NOT_ENOUGH_QUOTA: App s~is-now-illegal does not have enough quota
    </Details>
</Error>
```

**Comment by ivanseidel** [comment]
That's because our 20$ limit on the CDN has been reached 🤕 
We don't need code fixes, we are going to need some money in the end of the month haha
(Problem should be fixed in the next few minutes)

**Comment by ivanseidel** [comment]
Fixed...
