### ISSUE TITLE
Size of GIFs

### ISSUE THREAD

**Issue by kamikazechaser** [ivanseidel/Is-Now-Illegal#16]
I feel the size of the gifs generated are rather large, and thus not suitable for most platforms. I have made a bot for telegram (you can find it [here](https://telegram.me/isnowillegalbot)) and the gif size is 5 times larger than most gifs. I suggest a lossless compression of the gifs (gifsicle ports for python?) before pushing them to the cloud. That will both save you costs on Google Cloud Platform and make sharing the gifs easier. I wouldn't want to create a new service just to compress them before use. Great project by the way!

cc: #8

**Comment by customstickers** [comment]
[Gifsicle](https://www.lcdf.org/gifsicle/) sounds like a good idea to start with - i've just tested it and it reduced the 5MB of https://customsticke.rs/media/TEST.gif to 3MB of https://customsticke.rs/media/TESTgifsicle.gif with `gifsicle --optimize=3`

UPDATE: 2MB - https://customsticke.rs/media/TESTgifsiclelossy80.gif  with `gifsicle -O3 --lossy=80` from https://github.com/pornel/giflossy/releases/tag/lossy%2F1.82.1

UPDATE#2: 1MB with half frames - https://customsticke.rs/media/TESTgifsiclelossy80halfframes.gif (with https://customsticke.rs/media/gifsicle_remove2.sh - modified version of https://gist.github.com/aug2uag/0906c80efb9fd6067b54)

**Comment by manuel-di-iorio** [comment]
Have you considered using .webp ?
It's a lossless animated picture format.
For http://isnowillegal.com/?legality, I tested with http://www.online-convert.com and the size is half than gif

.gif 4.9 MB
.wepb 2.39 MB

But of course, optimizing the gif (losslessy) and dropping some not-important frames will generally help

**Comment by qgustavor** [comment]
@manuel-di-iorio I think the problem with WebP is the poor browser support: http://caniuse.com/#feat=webp

~~How about using some video format?~~ Video formats don't work in `<img>` tags... as noted [in WebP FAQ](https://developers.google.com/speed/webp/faq#why_should_i_use_animated_webp).

**Comment by brunolemos** [comment]
Hi guys, thanks for your ideas!

I just deployed a new version with the optimizations you suggested.
I removed some frames and applied compression using `gifsicle`.

The new gifs will now have only 1.2MB instead of 5.1MB!
That will have huge impact on the server costs, for sure!
