### ISSUE TITLE
Make Watermark Optional

### ISSUE THREAD

**Issue by ghost** [ivanseidel/Is-Now-Illegal#18]
Watermarks are the bane of my existence. Please consider removing the watermark from the gifs, or adding an option to disable them.

**Comment by brunolemos** [comment]
I believe we are not going to remove it because it's the only way to make people know the website and generate more gifs. 

If there is no watermark, the viral effect wouldn't exist.
I'll leave this open to wait for more opinions.

**Comment by 110Percent** [comment]
If you really want to remove the watermark, I'd suggest you make a fork and remove it yourself.

**Comment by manuel-di-iorio** [comment]
@110Percent https://github.com/ivanseidel/Is-Now-Illegal/commit/d2c78b701b43bf52a05dd600aa628fba2c033739 
They have not taken well your comment XD

**Comment by brunolemos** [comment]
Yeah we need this. And I kindly ask to not create copy projects removing it as well, unless it's a completely different gif (other scene from trump).
