### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by manuel-di-iorio** [ivanseidel/Is-Now-Illegal#2]
Cool project! :) But seems like your app ran out of quota :1st_place_medal: 
> The App Engine application does not have enough quota

http://isnowillegal.com/?test
https://storage.googleapis.com/is-now-illegal.appspot.com/gifs/TEST.gif

```This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
    <Code>InsufficientQuota</Code>
    <Message>
        The App Engine application does not have enough quota.
    </Message>
    <Details>
        NOT_ENOUGH_QUOTA: App s~is-now-illegal does not have enough quota
    </Details>
</Error>
```

**EDIT:** Now it is working, I suspect that the app quota usage has been reset. However, I leave this opened for review :+1:

**Comment by ivanseidel** [comment]
Yeah. I placed a few dollars for the limit. Never expected to have that being spend in a few hours 😨

**Comment by brunolemos** [comment]
I just increased the Google Cloud limit to $300.

**Comment by brunolemos** [comment]
Reopening because it's down again. Someone posted on [Hacker News](https://news.ycombinator.com/item?id=13556794) and other big sites.

> FIREBASE WARNING: Specified Firebase database has reached its Peak Connections limit.  If you are the Firebase owner, consider upgrading.

**Comment by pmargreff** [comment]
again

**Comment by ivanseidel** [comment]
One problem after the other, only because we tought 50 simultaneous users would be the limit. We have 4x that, and Firebase is complaining...

5 Instances running the GIF generation queue right now. Let's see if it scales properly now

**Comment by ivanseidel** [comment]
Thanks for the tip @pmargreff ! :D 

Should be fixed now...
