### ISSUE TITLE
Form UI improvement.

### ISSUE THREAD

**Issue by ctrlaltvikas** [ivanseidel/Is-Now-Illegal#21]
The illegalize word is getting out of the form on ubuntu 16.04- Firefox. Please check.

**Comment by joaopedrovbs** [comment]
This has already been fixed? @vikaskyadav please provide more information as which resolution you're on and if the problem persists!

**Comment by brunolemos** [comment]
@joaopedrovbs can you check this on firefox?  its probably a media query issue

**Comment by joaopedrovbs** [comment]
Checked out on firefox for mac and the issue really happens when the width is between 1000 - 1200 px

**Comment by ctrlaltvikas** [comment]
Yeah. You already resolved the issue. Forgot to ping you back. Working fine now. Awesome stuff.
