### ISSUE TITLE
Some gifs do not have watermark and don't loop

### ISSUE THREAD

**Issue by Metatronius** [ivanseidel/Is-Now-Illegal#26]
Some gifs don't have watermarks and don't loop, presumably because they were generated before watermarks were added and the database never got reset.

**Comment by brunolemos** [comment]
@Metatronius that's possible... which one did you see?

**Comment by Metatronius** [comment]
http://isnowillegal.com/?meme
http://isnowillegal.com/?anime

These are the ones I know about. Probably more. I'd just delete all entries from before the watermark change.

**Comment by brunolemos** [comment]
They seem to be correct now, maybe @ivanseidel fixed it, it wasn't me.
