### ISSUE TITLE
is this illegal ?

### ISSUE THREAD

**Issue by kwiss** [ivanseidel/Is-Now-Illegal#28]
![http://isnowillegal.com/?5mo%20gif](https://storage.googleapis.com/is-now-illegal.appspot.com/gifs/5MO%20GIF.gif)

**Comment by brunolemos** [comment]
5MO?

**Comment by CyberiumShadow** [comment]
He meant 5 MB

**Comment by brunolemos** [comment]
Well its now 1.2MB since  https://github.com/ivanseidel/Is-Now-Illegal/commit/166c4999c88eefc110382af7cb755334714f2f1e

**Comment by kwiss** [comment]
@brunolemos yeah more spread accross the web!!!
