### ISSUE TITLE
On prod, share links don't work

### ISSUE THREAD

**Issue by schas002** [ivanseidel/Is-Now-Illegal#34]
When clicking one, an Application Error from Heroku appears. A link is worth a hundred words: <http://share.isnowillegal.com/jQuery>.

**Comment by ivanseidel** [comment]
Thanks for warning us.

Heroku free dyno hours on the share server have ended, so we are going to transfer it to another account.

**Comment by schas002** [comment]
Okay :D

(Well, there's always the Patreon, and we might want to feed the share server with dyno fees from the Patreon too... ;])

**Comment by ivanseidel** [comment]
Fixed it... The way was to set to a Hobby dyno ($7/month). I will try to set it back to free on the beginning of the next month. 

Can you check if it's ok there?

Thanks!

**Comment by schas002** [comment]
It's working now :D

**Comment by ivanseidel** [comment]
great 🎉
