### ISSUE TITLE
Lossy compress the gifs

### ISSUE THREAD

**Issue by gregschoen** [ivanseidel/Is-Now-Illegal#36]
```
gifsicle -O3 --lossy=200 --colors 256 -o GIFS-200-lossy-compressed.gif GIFS-original.gif
```

Made the image > 50% smaller:

```
1.6M GIFS-200-lossy-compressed.gif
4.8M GIFS-original.gif
```

I believe this is the lossy gifsicle version I'm using:

https://github.com/pornel/giflossy

**Comment by brunolemos** [comment]
Thanks @gregschoen, we are already using it! 
Check this commit: https://github.com/ivanseidel/Is-Now-Illegal/commit/166c4999c88eefc110382af7cb755334714f2f1e
