### ISSUE TITLE
isnowillegal.com is now illegal?

### ISSUE THREAD

**Issue by renannprado** [ivanseidel/Is-Now-Illegal#39]

**Comment by brunolemos** [comment]
cc @ivanseidel

**Comment by ivanseidel** [comment]
Costs were about R$150 per month, witch led me to shutdown.. we need to find a cheaper option, using microservices maybe?

**Comment by ivanseidel** [comment]
<img width="1038" alt="screen shot 2018-07-11 at 7 41 52 pm" src="https://user-images.githubusercontent.com/3102127/42603046-8c2cd77c-8542-11e8-9bc6-c07bc88265e2.png">

**Comment by renannprado** [comment]
It's back!
