### ISSUE TITLE
 WoW Congratulations!

### ISSUE THREAD

**Issue by Cyber-MA** [ivanseidel/Is-Now-Illegal#4]
WoW Congratulations! Perfect job! 
Hahaha

**Comment by brunolemos** [comment]
Thanks @Cyber-MA! Feel free to contribute! 😀

**Comment by kucukkanat** [comment]
How do you really insert the text on images and make them all a gif ? 
I mean the moving text.
Can you explain the algorithm a bit on that ? 
Thanks

**Comment by ivanseidel** [comment]
Thank you @Cyber-MA :)

Hi @kucukkanat! We do a kind of rotoscopy, where we try to mach a real media, on top of another.

To do that, we extracted (in this case, manually to speedup processing later) the 3 corners of the paper along the frames.

We then, generate the "paper" image, and apply it in the image with an [Affine Transformation](http://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html?highlight=warpaffine), and generate the gif after that with the generated frames.

Check the folder `rotoscope` to understand more ;)
